### ISSUE TITLE
Error: Read Step 

### ISSUE THREAD

**Issue by younesdessia** [Dessia-tech/volmdlr#1115]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request

* **What is the current behavior?**

I read step (Assembly) on the platform and locally with dev volmdlr, and I got this error:
```
volume_model._check_platform()
Traceback (most recent call last):
  File "/home/younes/.local/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3442, in run_code
    exec(obj_code, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-b3d15af50e47>", line 1, in <module>
    volume_model._check_platform()
  File "/home/younes/Bureau/DESSIA_WORK/dessia_common/dessia_common/core.py", line 555, in _check_platform
    return self.check_platform().raise_if_above_level(level=level)
  File "/home/younes/Bureau/DESSIA_WORK/dessia_common/dessia_common/core.py", line 567, in check_platform
    deserialized_object = self.dict_to_object(decoded_json)
  File "/home/younes/Bureau/DESSIA_WORK/dessia_common/dessia_common/serialization.py", line 68, in dict_to_object
    obj = dict_to_object(dict_=dict_, force_generic=force_generic, global_dict=global_dict,
  File "/home/younes/Bureau/DESSIA_WORK/dessia_common/dessia_common/serialization.py", line 310, in dict_to_object
    global_dict, pointers_memo = update_pointers_data(global_dict=global_dict, current_dict=dict_,
  File "/home/younes/Bureau/DESSIA_WORK/dessia_common/dessia_common/serialization.py", line 629, in update_pointers_data
    pointers_memo.update(dereference_jsonpointers(current_dict))
  File "/home/younes/Bureau/DESSIA_WORK/dessia_common/dessia_common/serialization.py", line 670, in dereference_jsonpointers
    order = deserialization_order(dict_)
  File "/home/younes/Bureau/DESSIA_WORK/dessia_common/dessia_common/serialization.py", line 643, in deserialization_order
    raise NotImplementedError('Cycles in jsonpointers not handled')
NotImplementedError: Cycles in jsonpointers not handled
```
I did check_platform, when I save in json it goes through but when I open the json I get the same error

knowing that the platform, checks the to_dict (which passed) and the dict_to_object which triggers an error
no problem on volmdlr 0.13 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: 
  - commit:  
  - python version:

**Comment by AxelRinghausen** [comment]
Solved in dessia_common 0.13.6 and 0.14.2
