### ISSUE TITLE
contour2D: merge_with()

### ISSUE THREAD

**Issue by ziedsallem** [Dessia-tech/volmdlr#486]
* **I'm submitting a ...**
  - [ X] bug report
  - [ ] feature request

* **What is the current behavior?**
Traceback (most recent call last):
  File "/home/sallem/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3552, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-ad582ae6ab94>", line 1, in <cell line: 1>
    runfile('/home/sallem/Documents/git/ElectricMachines/scripts/motor_exemple_2.py', wdir='/home/sallem/Documents/git/ElectricMachines/scripts')
  File "/home/sallem/Téléchargements/pycharm-community-2021.3.3/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/sallem/Téléchargements/pycharm-community-2021.3.3/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/sallem/Documents/git/ElectricMachines/scripts/motor_exemple_2.py", line 108, in <module>
    ext_contour = ext_contour[0].merge_with(notch)
  File "/home/sallem/Documents/git/volmdlr/volmdlr/wires.py", line 2217, in merge_with
    contours = volmdlr.wires.Contour2D.contours_from_edges(merged_primitives)
  File "/home/sallem/Documents/git/volmdlr/volmdlr/wires.py", line 1215, in contours_from_edges
    contours_primitives_lists = cls.contours_primitives_touching_primitives(touching_primitives)
  File "/home/sallem/Documents/git/volmdlr/volmdlr/wires.py", line 1131, in contours_primitives_touching_primitives
    prim2_split = prim2.split(intersection)
  File "/home/sallem/Documents/git/volmdlr/volmdlr/edges.py", line 2028, in split
    abscissa = self.abscissa(split_point)
  File "/home/sallem/Documents/git/volmdlr/volmdlr/edges.py", line 1727, in abscissa
    raise ValueError('Point not in arc')
ValueError: Point not in arc

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

pt1 = vm.Point2D(0.002 / 2, 0.025 / 2)
pt2 = vm.Point2D(0, 0.012539936203984454)
pt3 = vm.Point2D(-0.002 / 2, 0.025 / 2)
pt4 = vm.Point2D(0.002 / 2,
                 0.025 / 2 + 0.0015)
pt5 = vm.Point2D(-0.002 / 2,
                 0.025 / 2 + 0.0015)
rls = p2d.OpenedRoundedLineSegments2D([pt1, pt4, pt5, pt3], {})
arc2 = vmedges.Arc2D(pt1, pt2, pt3)
contour2d = vmwires.Contour2D(rls.primitives + [arc2])
ext_contour = vmwires.Circle2D(vm.O2D, 0.012539936203984454)
ext_contour = ext_contour.merge_with(contour2d)
ax = ext_contour[0].plot()
for i in range(1, 12):
    notch = contour2d.rotation(vm.O2D, i * 2 * math.pi / 12)
    notch.plot(ax=ax, color='r')
    ext_contour = ext_contour[0].merge_with(notch)

* **What is the expected behavior?**
merge with a circle after the rotation of the contour

* **What is the motivation / use case for changing the behavior?**

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: em_mesh
  - commit:  
  - python version:

**Comment by sbendjebla** [comment]
Probably fixed with #490 #492 #493 
The result:
![image](https://user-images.githubusercontent.com/68638483/195609521-c88eb923-b1a7-46f8-a369-36b0e382b2d7.png)
